#set -g default-terminal screen-256color
bind r source-file ~/.tmux.conf
# THEME
set -g status-bg yellow
set -g status-fg black
set -g status-interval 2
set -g status-right-length 120
set -g status-left ' #[bg=green] #[fg=red](#S) (#P) '
set -g status-justify centre
set -g status-right ' #[bg=blue] #[fg=gray]#(bash ~/scripts/tmux.sh)'
