#!/bin/sh

userresources=$HOME/.Xresources

bluez=$(bluetoothctl info | grep "Name: FILCO")

sysresources=/etc/X11/xinit/.Xresources
#sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -z "$bluez" ]
then
    usermodmap=$HOME/.Xmodmap
else
    usermodmap=$HOME/.xmodmap
fi


# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

#if [ -f $sysmodmap ]; then
#    xmodmap $sysmodmap
#fi

if [ -f "$userresources" ]; then

    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


#exec dwm

session=${1}

case $session in
    dwm           ) exec dwm;;
    emacs         ) exec emacs;;
    # No known session, try to run it as command
    *             ) exec $1;;
esac



