# If you come from bash you might have to change your $PATH.
export PATH=/usr/local/texlive/2021/bin/x86_64-linux:/home/ren/.local/bin:$PATH
if [ -d "$HOME/adb-fastboot/platform-tools" ] ; then
    export PATH="$HOME/adb-fastboot/platform-tools:$PATH"
    fi
# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="amuse"
ZSH_THEME="af-magic"
# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git sudo colorize zsh-completions aws fzf zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh


# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG="en_US.utf8"
export LC_ALL="en_US.utf8"
export LC_CTYPE="en_US.utf8"
export EDITOR='nvim'
# Preferred editor for local and remote sessions

# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

#ZSH_COLORIZE_TOOL=chroma

#ZSH_COLORIZE_STYLE="colorful"

export QT_QPA_PLATFORMTHEME=qt5ct

alias px='proxychains4'
alias ne='clear && echo "\n" && neofetch --ascii_distro Linux'
alias xm="xmodmap .Xmodmap"
alias xn="xmodmap .xmodmap"
alias bl="bluetoothctl"
alias is="sudo iw dev wlan0 scan | grep SSID"
alias io="sudo iw dev wlan0 connect CNU"
alias ik="sudo iw dev wlan0 disconnect"
alias ih="iw dev wlan0 info"
alias se="./scripts/se.sh"
alias sd="./scripts/sd.sh"
alias em="emacs -nw"
alias ra="ranger"
alias vv="v2ray -c ~/scripts/config.json"
alias psy="sudo pacman -Syyu"
alias ps="sudo pacman -S"
alias pr="sudo pacman -Rns"
alias pq="sudo pacman -Q"
alias cs="curl --socks5 127.0.0.1:1080"
alias vim="nvim"
alias mu="proxychains4 neomutt"
alias ke="sudo loadkeys i386/qwerty/emacs2.map.gz"
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode'
#export FZF_DEFAULT_OPTS='--bind=ctrl-t:top,change:top --bind ctrl-e:down,ctrl-u:up'
#export FZF_DEFAULT_OPTS='--preview "[[ $(file --mime {}) =~ binary ]] && echo {} is a binary file || (ccat --color=always {} || highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500"  --preview-window :noborder '
#export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_COMPLETION_TRIGGER='f'
export FZF_TMUX=1
export FZF_TMUX_HEIGHT='100%'

source /usr/share/fzf/completion.zsh

source $HOME/.oh-my-zsh/custom/plugins/fzf-tab-completion/zsh/fzf-zsh-completion.sh


zstyle ':completion:*' fzf-search-display true

man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

#bindkey '^F' vi-forward-char
#bindkey '' vi-backward-char
#bindkey '^P' up-line-or-history
#bindkey '^N' down-line-or-history

#bindkey -v

#export KEYTIMEOUT=1
